### ISSUE TITLE
error parsing gpx 1.1 file (from la-flamme-rouge website)

### ISSUE THREAD

**Issue by luogni** [georust/gpx#48]
```
thread 'main' panicked at 'Error parsing gpx file.: Error(InvalidElementLacksAttribute("version", "gpx"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/context.rs:160:32
```

[fail.tar.gz](https://github.com/georust/gpx/files/6435339/fail.tar.gz)

**Comment by luogni** [comment]
if I add the `version` attribute it fails with:
```
thread 'main' panicked at 'Error parsing gpx file.: Error(InvalidChildElement("desc", "metadata"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/context.rs:160:32
```
